import type { FC, ImgHTMLAttributes, SyntheticEvent } from "react";
import { useState } from "react";

interface OptimizedImageProps extends ImgHTMLAttributes<HTMLImageElement> {
  /** Full src path or Vite-resolved import (may include extension). */
  src: string;
  alt: string;
  /**
   * When true, emit a <picture> with a WebP sibling (base.webp) as the
   * preferred source, and the original extension as the fallback source.
   * Only enable this if BOTH files actually exist on disk (run
   * `npm run optimize:images` to generate WebP siblings for every PNG/JPG
   * in src/assets and public/). If a sibling is missing, the browser will
   * pick the first supported <source>, get a 404, and render nothing —
   * so this is opt-in, not opt-out.
   */
  webp?: boolean;
}

const RASTER_EXT_RE = /\.(png|jpe?g|webp)$/i;
const STRIP_EXT_RE = /\.(png|jpe?g|webp)$/i;

const stripExtension = (path: string) => path.replace(STRIP_EXT_RE, "");

const OptimizedImage: FC<OptimizedImageProps> = ({
  src,
  alt,
  webp = false,
  loading = "lazy",
  decoding = "async",
  onError,
  ...props
}) => {
  // ── Last-resort runtime guard: if anything in the <picture> chain fails
  //    (404 webp source, bad sibling, anything), re-render as a plain <img>
  //    pointing at the original imported src so the user always sees pixels.
  const [degraded, setDegraded] = useState(false);

  const hasRasterExt = RASTER_EXT_RE.test(src);

  const handleError = (e: SyntheticEvent<HTMLImageElement>) => {
    setDegraded(true);
    onError?.(e);
  };

  // ── No picture mode: plain <img> with original src (guaranteed to exist
  //    because Vite bundled it from the import) ────────────────────────────
  if (!webp || !hasRasterExt || degraded) {
    return (
      <img
        src={src}
        alt={alt}
        loading={loading}
        decoding={decoding}
        onError={handleError}
        {...props}
      />
    );
  }

  const base = stripExtension(src);
  const isWebpSrc = /\.webp$/i.test(src);
  const isJpegSrc = /\.jpe?g$/i.test(src);

  let preferredSrc: string;
  let preferredType: string;
  let fallbackSrc: string;
  let fallbackType: string;
  let imgSrc: string;

  if (isWebpSrc) {
    // ── Original import IS a .webp — don't fabricate a missing PNG sibling.
    //    Just emit the known webp path on both sources and the img fallback.
    preferredSrc = src;
    preferredType = "image/webp";
    fallbackSrc = src;
    fallbackType = "image/webp";
    imgSrc = src;
  } else if (isJpegSrc) {
    // ── Original import IS a .jpg/.jpeg — sibling .webp generated by
    //    optimize-images.js is preferred; original jpg is the fallback.
    preferredSrc = `${base}.webp`;
    preferredType = "image/webp";
    fallbackSrc = `${base}.jpg`;
    fallbackType = "image/jpeg";
    imgSrc = fallbackSrc;
  } else {
    // ── Original import IS a .png — sibling .webp preferred; original png
    //    fallback.
    preferredSrc = `${base}.webp`;
    preferredType = "image/webp";
    fallbackSrc = `${base}.png`;
    fallbackType = "image/png";
    imgSrc = fallbackSrc;
  }

  return (
    <picture>
      <source srcSet={preferredSrc} type={preferredType} />
      {fallbackSrc !== preferredSrc && (
        <source srcSet={fallbackSrc} type={fallbackType} />
      )}
      <img
        src={imgSrc}
        alt={alt}
        loading={loading}
        decoding={decoding}
        onError={handleError}
        {...props}
      />
    </picture>
  );
};

export default OptimizedImage;
